"use client";

import { useState } from "react";
import { Activity, ArrowUpRight, Pause, Play, RotateCcw } from "lucide-react";
import { plantMetrics, readingFor, SCENARIOS, STAGES, statusFor, type Scenario } from "./process";
import type { OperationsDashboardProps } from "./OperationsDashboard";
import s from "./reference-board.module.css";

const fmt = (n: number) => n.toLocaleString("fr-FR", { maximumFractionDigits: 1 });
const states = { normal: "Nominal", warning: "Impact propagé", critical: "Défaut actif" };
export function ReferenceBoard({ simulation, selected, onSelect, onReset, onOpen3d }: OperationsDashboardProps) {
  const [tab, setTab] = useState("Vue d’ensemble");
  const [windowSize, setWindowSize] = useState(30);
  const { seconds, scenario, running, speed, dispatch, samples, events, acknowledged } = simulation;
  const m = plantMetrics(seconds, scenario);
  const active = STAGES.find(x => x.id === selected) ?? STAGES[6];
  const history = samples.filter(x => x.seconds >= seconds - windowSize);
  const affected = STAGES.filter(x => statusFor(x.id, scenario) !== "normal");
  const ratio = m.oil / m.throughput * 100;
  const line = history.map((x, i) => `${40 + i * 410 / Math.max(1, history.length - 1)},${165 - x.readings[active.id] / (active.nominal * 1.5) * 130}`).join(" ");
  const health = STAGES.map(x => statusFor(x.id, scenario) === "normal" ? 98 : statusFor(x.id, scenario) === "warning" ? 70 : 40);
  const polygon = (values: number[]) => values.map((v, i) => { const a = i * Math.PI * 2 / 7 - Math.PI / 2; return `${130 + Math.cos(a) * v * .86},${112 + Math.sin(a) * v * .86}`; }).join(" ");
  return <main className={s.board}>
    <nav className={s.nav} aria-label="Sections du tableau de bord"><div className={s.tabs}>{["Vue d’ensemble", "Diagnostics", "Santé des actifs", "Efficacité"].map(x => <button key={x} aria-pressed={tab === x} onClick={() => setTab(x)}>{x}</button>)}</div><span className={s.live}>● {running ? "SIMULATION EN COURS" : "SIMULATION EN PAUSE"}</span></nav>
    <div className={s.heading}><div><span className={s.eyebrow}>SITE A / HUILERIE DE PALME</span><h1>{tab === "Vue d’ensemble" ? "Le procédé, en un regard." : tab}</h1></div><button onClick={onOpen3d}>Explorer l’usine en 3D <ArrowUpRight size={15} /></button></div>
    <div className={s.controls}><label>Scénario <select value={scenario} onChange={e => dispatch({ type: "scenario", value: e.target.value as Scenario })}>{SCENARIOS.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div><button aria-label={running ? "Mettre en pause" : "Reprendre"} onClick={() => dispatch({ type: "toggle" })}>{running ? <Pause size={15} /> : <Play size={15} />}</button><span>{Math.floor(seconds / 60).toString().padStart(2,"0")}:{(seconds % 60).toString().padStart(2,"0")}</span><select aria-label="Vitesse de simulation" value={speed} onChange={e => dispatch({ type: "speed", value: +e.target.value })}>{[1,2,4].map(x => <option key={x} value={x}>{x}×</option>)}</select><button onClick={onReset} aria-label="Réinitialiser la simulation"><RotateCcw size={15} /></button></div></div>
    {tab !== "Vue d’ensemble" && <section className={`${s.card} ${s.detail}`} aria-live="polite"><h2>{tab}</h2>{tab === "Diagnostics" ? <p>{SCENARIOS.find(x=>x.id===scenario)?.description} {affected.length} unité(s) affectée(s). L’acquittement confirme la lecture ; le scénario nominal rétablit le procédé.</p> : tab === "Santé des actifs" ? <div className={s.healthList}>{STAGES.map(x=><button key={x.id} onClick={()=>onSelect(x.id)}>{x.code} · {x.name} — {states[statusFor(x.id,scenario)]}</button>)}</div> : <p>Extraction : {fmt(ratio)}%. Débit actuel : {fmt(m.throughput/30*100)}% de la référence de 30 t/h. Le modèle réduit les débits ensemble lors d’un défaut ; il ne simule pas une variation indépendante du rendement.</p>}</section>}
    <div className={s.grid}>
      <section className={s.card}><h2>Production d’huile <Activity size={17} /></h2><p>Débit d’huile brute</p><div className={s.big}>{fmt(m.oil)} <small>t/h</small></div><span className={s.teal}>{scenario === "normal" ? "Production nominale" : "Production affectée"}</span><div className={s.divider}/><p>Régimes de fruits frais</p><strong className={s.medium}>{fmt(m.throughput)} <small>t/h</small></strong><p>7 unités de procédé connectées</p></section>
      <section className={`${s.card} ${s.wide}`}><h2>Évolution de la production <select aria-label="Fenêtre du graphique" value={windowSize} onChange={e => setWindowSize(+e.target.value)}><option value={30}>30 s</option><option value={60}>60 s</option><option value={120}>120 s</option></select></h2><p>Huile brute · t/h · échantillons de simulation</p><svg viewBox="0 0 480 190" role="img" aria-label="Historique du débit d’huile brute en tonnes par heure">{[0,2,4,6,8].map(v => <g key={v}><line x1="35" x2="467" y1={160-v*17} y2={160-v*17} className={s.gridline}/><text x="12" y={164-v*17}>{v}</text></g>)}{history.map((x,i) => <rect key={`${x.seconds}-${i}`} x={40+i*425/history.length} y={160-x.metrics.oil*17} width={Math.max(2,310/history.length)} height={x.metrics.oil*17} rx="3" fill={i%2 ? "#27bcb7" : "#3194cc"}><title>{`${x.seconds}s : ${fmt(x.metrics.oil)} t/h`}</title></rect>)}<text x="35" y="185">{history[0]?.seconds}s</text><text x="420" y="185">{seconds}s</text></svg></section>
      <section className={s.card}><h2>Santé du système</h2><svg viewBox="0 0 260 230" role="img" aria-label={`Santé globale ${m.health} pour cent. ${affected.length} unités affectées.`}>{[25,50,75,100].map(v => <polygon key={v} points={polygon(Array(7).fill(v))} className={s.radarGrid}/>)}<polygon points={polygon(health)} fill="#27bcb733" stroke="#42cfce" strokeWidth="2"/>{STAGES.map((x,i) => {const a=i*Math.PI*2/7-Math.PI/2; return <text key={x.id} x={130+Math.cos(a)*110} y={116+Math.sin(a)*105} textAnchor="middle">{x.code.split('-')[0]}</text>;})}</svg><div className={s.center}><strong>{m.health}%</strong><span>Indice global simulé</span></div></section>
      <section className={s.card}><h2>Unités & propagation</h2><div className={s.units}>{STAGES.map(x => <button key={x.id} aria-pressed={active.id === x.id} onClick={() => onSelect(x.id)}><span>{x.name}</span><span className={statusFor(x.id,scenario) === "normal" ? s.teal : s.warning}>{statusFor(x.id,scenario) === "normal" ? "●" : "▲"}<span className={s.sr}>{states[statusFor(x.id,scenario)]}</span></span></button>)}</div></section>
      <section className={`${s.card} ${s.wide}`}><h2>{tab === "Efficacité" ? "Bilan de transformation" : "Rendement d’extraction"}<span className={s.tag}>OER</span></h2><div className={s.efficiency}><div className={s.ring}><svg viewBox="0 0 160 160" aria-label={`Rendement d’extraction ${fmt(ratio)} pour cent`} role="img"><circle cx="80" cy="80" r="62" fill="none" stroke="#557180" strokeWidth="17"/><circle cx="80" cy="80" r="62" fill="none" stroke="#29c4bd" strokeWidth="17" strokeDasharray={`${ratio/100*390} 390`} transform="rotate(-90 80 80)"/></svg><div><strong>{fmt(ratio)}%</strong><span>Huile / régimes</span></div></div><div><p>Flux du procédé</p><dl><div><dt>Régimes entrants</dt><dd>{fmt(m.throughput)} t/h</dd></div><div><dt>Huile brute</dt><dd>{fmt(m.oil)} t/h</dd></div><div><dt>Autres flux¹</dt><dd>{fmt(m.throughput-m.oil)} t/h</dd></div></dl><p>¹ Différence de débit, sans détail de composition.</p></div></div></section>
      <section className={s.card}><h2>Réseau vapeur</h2><p>BLR-01 · Chaudière biomasse</p><div className={s.big}>{fmt(m.steam)} <small>bar</small></div><p>Référence nominale <b>18 bar</b></p><div className={s.divider}/><p>Stérilisation · STR-01</p><strong className={s.medium}>{fmt(readingFor(STAGES[1],seconds,scenario))} <small>bar</small></strong><p className={scenario === "steam" ? s.warning : s.teal}>{scenario === "steam" ? "▲ Baisse de pression propagée" : "● Alimentation nominale"}</p></section>
      <section className={s.card}><h2>Diagnostic équipement</h2><label className={s.assetLabel}>Équipement<select value={active.id} onChange={e => { const x=STAGES.find(x=>x.id===e.target.value); if(x) onSelect(x.id); }}>{STAGES.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><p>{active.metric}</p><strong className={s.medium}>{fmt(readingFor(active,seconds,scenario))} <small>{active.unit}</small></strong><p className={statusFor(active.id,scenario)==="normal" ? s.teal : s.warning}>{states[statusFor(active.id,scenario)]}</p><p>{active.description}</p><button onClick={() => { onSelect(active.id); onOpen3d(); }}>Inspecter en 3D <ArrowUpRight size={14}/></button></section>
      <section className={`${s.card} ${s.wide}`}><h2>Mesure simulée vs référence</h2><p>{active.code} · {active.metric} ({active.unit})</p><svg viewBox="0 0 480 200" role="img" aria-label={`${active.metric}, mesure simulée et référence nominale ${active.nominal} ${active.unit}`}>{[0,.5,1,1.5].map(v=><g key={v}><line x1="40" x2="450" y1={165-v/1.5*130} y2={165-v/1.5*130} className={s.gridline}/><text x="0" y={169-v/1.5*130}>{fmt(active.nominal*v)}</text></g>)}<line x1="40" x2="450" y1={165-130/1.5} y2={165-130/1.5} stroke="#429ce1" strokeDasharray="6 5"/><polyline points={line} fill="none" stroke="#34d5c9" strokeWidth="2.5"/>{history.length===1 && <circle cx="40" cy={165-history[0].readings[active.id]/(active.nominal*1.5)*130} r="4" fill="#34d5c9"/>}<text x="40" y="194">{history[0]?.seconds}s</text><text x="425" y="194">{seconds}s</text></svg><p><span className={s.teal}>━ Mesure</span>　<span>┄ Référence nominale</span></p></section>
      <section className={s.card}><h2>Journal de simulation</h2><div className={s.events}>{events.slice(0,3).map(x=><div key={x.id}><small>{x.seconds}s</small><strong>{x.title}</strong><p>{x.detail}</p></div>)}</div>{scenario!=="normal" && <button disabled={acknowledged} onClick={()=>dispatch({type:"acknowledge"})}>{acknowledged ? "Alerte acquittée · défaut actif" : "Acquitter l’alerte"}</button>}</section>
    </div>
    <footer className={s.footer}><span>STEAM VALUE™ · Jumeaux numériques composés</span><span>Données simulées · Aucune commande d’équipement réel</span></footer>
  </main>;
}
